// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzkpkgvicyeeqfsnffwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56a3BrZ3ZpY3llZXFmc25mZndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NjA2OTMsImV4cCI6MjA1OTUzNjY5M30.hfwBjJJTpwioYwTT8S9xjDWUCVEeQZmKTRX3TKsz6lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);